services:
  db:
    image: postgres:15-alpine
    container_name: faxinei-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: faxinei
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/pg:/data/postgres # Salva os dados na sua pasta local para não perder nada

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faxinei-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:docker@db:5432/faxinei
      JWT_SECRET: changeme123456
      JWT_EXPIRES_IN: 7d
      PORT: 3333
      NODE_ENV: production
    ports:
      - '3333:3333'
    restart: unless-stopped
